set  -g default-terminal "screen-256color"
set  -g base-index      1
setw -g pane-base-index 1

set  -g default-shell "$SHELL"

set -g status-keys vi
set -g mode-keys   vi

bind -N "Select pane to the left of the active pane" h select-pane -L
bind -N "Select pane below the active pane" j select-pane -D
bind -N "Select pane above the active pane" k select-pane -U
bind -N "Select pane to the right of the active pane" l select-pane -R

bind -r -N "Resize the pane left by 5" \
  H resize-pane -L 5
bind -r -N "Resize the pane down by 5" \
  J resize-pane -D 5
bind -r -N "Resize the pane up by 5" \
  K resize-pane -U 5
bind -r -N "Resize the pane right by 5" \
  L resize-pane -R 5


# rebind main key: `
unbind C-b
set -g prefix `
bind -N "Send the prefix key through to the application" \
  ` send-prefix

bind-key -N "Kill the current window" & kill-window
bind-key -N "Kill the current pane" x kill-pane

set  -g mouse             on
set  -g focus-events      off
setw -g aggressive-resize off
setw -g clock-mode-style  12
set  -s escape-time       0
set  -g history-limit     2000

set -g renumber-windows on
set -g repeat-time 1000

set -g status-style bg=default,fg=black,bright
set -g status-left ""
set -g status-right "#[fg=black,bright]#S"

set -g pane-border-lines simple
set -g pane-border-style fg=black,bright
set -g pane-active-border-style fg=magenta

set -g window-status-format "●"
set -g window-status-current-format "●"
set -g window-status-current-style "#{?window_zoomed_flag,fg=yellow,fg=magenta,nobold}"
set -g window-status-bell-style "fg=red,nobold"

bind s split-window -h
bind v split-window -v

bind - split-window -h
bind | split-window -v

